version: '3'

services:
  vuln-web:
    container_name: vuln-web
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - email=changeme@mail.com
        - password_email=changeme
    restart: unless-stopped
    volumes:
      - ./app:/var/www/html
    networks:
      - labs-net
    depends_on:
      - database
    ports:
      - 80:80
  database:
    image: mysql:5.7.22
    container_name: database
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: vulnerableweb1337
      MYSQL_DATABASE: vulnweb
      MYSQL_USER: vulnerableweb
      MYSQL_PASSWORD: vulnerableweb
    ports:
      - 3306:3306
    volumes:
      - ./conf/database.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    networks:
      - labs-net
networks:
  labs-net:
    driver: bridge
    driver_opts: 
      com.docker.network.enable_ipv6: "false"